source 'https://rubygems.org'

gem 'bundler', '~> 1.14'
gem 'http-cookie'
gem 'json'
gem 'logger'
gem 'rubocop', '~> 0.51'
gem 'rubocop-rspec', '~> 1.15.1'
gem 'swift_ingest', '~> 0.2.0'
gem 'test-unit'
gem 'vcr', '~> 3.0'
gem 'webmock'
